In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
house=pd.read_csv("house_price.csv")

In [3]:
house.head()

   Size  Bedrooms Location   Age    Price
0   859       1.0    Urban   2.0   586315
1  2469       3.0    Urban  26.0  1233388
2  2188       4.0    Rural  13.0  1069161
3  1681       2.0    Rural   4.0   830750
4  1668       4.0    Urban  25.0   928932

In [4]:
house_clean=house.copy()

In [5]:
house_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Size      220 non-null    int64
 1   Bedrooms  218 non-null    float64
 2   Location  219 non-null    str
 3   Age       219 non-null    float64
 4   Price     220 non-null    int64
dtypes: float64(2), int64(2), str(1)
memory usage: 9.8 KB

In [6]:
house_clean["Bedrooms"]=house_clean["Bedrooms"].fillna(house_clean["Bedrooms"].median())

In [7]:
house_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Size      220 non-null    int64
 1   Bedrooms  220 non-null    float64
 2   Location  219 non-null    str
 3   Age       219 non-null    float64
 4   Price     220 non-null    int64
dtypes: float64(2), int64(2), str(1)
memory usage: 9.8 KB

In [8]:
house_clean.head()

   Size  Bedrooms Location   Age    Price
0   859       1.0    Urban   2.0   586315
1  2469       3.0    Urban  26.0  1233388
2  2188       4.0    Rural  13.0  1069161
3  1681       2.0    Rural   4.0   830750
4  1668       4.0    Urban  25.0   928932

In [9]:
house_clean["Age"]=house_clean["Age"].fillna(house_clean["Age"].median())

In [10]:
house_clean["Location"]=house_clean["Location"].fillna(house_clean["Location"].mode()[0])

In [11]:
house_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Size      220 non-null    int64
 1   Bedrooms  220 non-null    float64
 2   Location  220 non-null    str
 3   Age       220 non-null    float64
 4   Price     220 non-null    int64
dtypes: float64(2), int64(2), str(1)
memory usage: 9.8 KB

In [12]:
house_clean["Location"].unique()

<ArrowStringArray>
['Urban', 'Rural']
Length: 2, dtype: str

In [13]:
house_clean["Location"]=house_clean["Location"].map({"Rural":0, "Urban":1})

In [14]:
house_clean.head()

   Size  Bedrooms  Location   Age    Price
0   859       1.0         1   2.0   586315
1  2469       3.0         1  26.0  1233388
2  2188       4.0         0  13.0  1069161
3  1681       2.0         0   4.0   830750
4  1668       4.0         1  25.0   928932

In [15]:
house_clean["Location"]

0      1
1      1
2      0
3      0
4      1
      ..
215    1
216    1
217    1
218    0
219    0
Name: Location, Length: 220, dtype: int64

In [16]:
x_reg=house_clean[["Size","Bedrooms","Location","Age"]]
y_reg=house_clean["Price"]

In [17]:
xr_train,xr_test,yr_train,yr_test=train_test_split(x_reg,y_reg,test_size=0.2,random_state=24)

In [18]:
len(xr_train)

176

In [19]:
len(xr_test)

44

In [20]:
xr_train

     Size  Bedrooms  Location   Age
11   2943       5.0         1  22.0
78   1977       2.0         0  30.0
72   1738       5.0         0  19.0
180  2855       5.0         1  23.0
151  1311       4.0         1   5.0
..    ...       ...       ...   ...
145  2656       3.0         1   1.0
87   1384       3.0         0   9.0
192  2077       2.0         1  23.0
131  1951       1.0         1  24.0
162  1611       5.0         0  12.0

[176 rows x 4 columns]

In [21]:
xr_test

     Size  Bedrooms  Location   Age
125  1978       2.0         0  28.0
19   1708       4.0         1  19.0
63   2924       3.0         1  14.0
142  1300       2.0         1  26.0
25   2163       1.0         0  21.0
121  2221       2.0         0  22.0
13   2439       4.0         1  30.0
103   667       5.0         1  20.0
158  1837       2.0         1  13.0
88   2455       2.0         1  28.0
104  2523       5.0         0  18.0
91   2542       3.0         1  12.0
205  1275       1.0         0  26.0
40   1038       4.0         1  27.0
0     859       1.0         1   2.0
26   1596       4.0         1  12.0
14   2336       3.0         0  23.0
29   1692       1.0         1   2.0
102  2542       4.0         1  16.0
69   1753       3.0         1   8.0
171   861       1.0         1  11.0
140  2960       5.0         0   1.0
48   2243       4.0         1  12.0
209  2480       4.0         0   4.0
113  1728       5.0         0  13.0
146   731       3.0         0   2.0
210  1263       1.0         0  15.0
51   1107       1.0         1  21.0
203  2295       3.0         1  17.0
212  2504       5.0         0  26.0
138  1466       1.0         1   1.0
152  2807       3.0         1  22.0
177  1029       1.0         1  23.0
127  2448       5.0         1  15.0
160  2991       1.0         1  21.0
124  2660       5.0         0   3.0
68    829       3.0         1  29.0
214  2382       3.0         1  10.0
111  2485       2.0         1  17.0
155  2206       1.0         1  23.0
202  1813       4.0         1  29.0
137   722       5.0         0  15.0
193  1500       1.0         0  16.0
165  2563       1.0         0   4.0

In [22]:
yr_train

11     1460324
78      930333
72      889386
180    1499912
151     831037
        ...
145    1421953
87      750284
192    1091631
131     908731
162     861348
Name: Price, Length: 176, dtype: int64

In [23]:
reg_model=LinearRegression()
reg_model.fit(xr_train,yr_train)

LinearRegression()

In [24]:
yr_pred=reg_model.predict(xr_test)

In [25]:
mae=mean_absolute_error(yr_test,yr_pred)
rmse=np.sqrt(mean_squared_error(yr_test,yr_pred))
r2=r2_score(yr_test,yr_pred)

In [26]:
print(f"MAE :{mae:.2f}")
print(f"RMSE :{rmse:.2f}")
print(f"r2 :{r2:.3f}")

MAE :36083.73
RMSE :44074.02
r2 :0.981

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [28]:
churn = pd.read_csv("customer_churn.csv")
X_cls = churn.drop(columns="Churn")
y_cls = churn["Churn"]

churn.head()

,MonthlyCharges,Tenure,ContractType,PaymentMethod,SupportCalls,Churn
0,49.67,38,One year,Electronic check,4,1
1,72.29,66,Month-to-month,Electronic check,1,0
2,64.52,28,One year,Credit card,1,0
3,46.62,4,Two year,Credit card,4,0
4,123.22,23,Month-to-month,Electronic check,2,1

In [29]:
num_cols = ["MonthlyCharges", "Tenure", "SupportCalls"]
cat_cols = ["ContractType", "PaymentMethod"]

In [30]:
preprocess = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]), num_cols),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

In [31]:
Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_cls, y_cls, test_size=0.20, random_state=42, stratify=y_cls
)

In [32]:
logistic_pipe = Pipeline([
    ("preprocess", preprocess),
    ("model", LogisticRegression(max_iter=1000))
])
logistic_pipe.fit(Xc_train, yc_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['MonthlyCharges', 'Tenure',
                                                   'SupportCalls']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['ContractType',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000))])

In [33]:
yc_pred = logistic_pipe.predict(Xc_test)
yc_prob = logistic_pipe.predict_proba(Xc_test)[:, 1]

In [34]:
print("Accuracy:", accuracy_score(yc_test, yc_pred))
print("Precision:", precision_score(yc_test, yc_pred, zero_division=0))
print("Recall:", recall_score(yc_test, yc_pred, zero_division=0))
print("F1-Score:", f1_score(yc_test, yc_pred, zero_division=0))
print("ROC-AUC:", roc_auc_score(yc_test, yc_prob))
print("\nConfusion Matrix:\n", confusion_matrix(yc_test, yc_pred))

Accuracy: 0.7666666666666667
Precision: 0.7142857142857143
Recall: 0.6521739130434783
F1-Score: 0.6818181818181818
ROC-AUC: 0.8081668625146886

Confusion Matrix:
 [[62 12]
 [16 30]]